# Generated by Django 4.1.3 on 2023-05-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("end_year", models.IntegerField(max_length=100)),
                ("intensity", models.IntegerField(max_length=100)),
                ("sector", models.CharField(max_length=100)),
                ("topic", models.CharField(max_length=100)),
                ("insight", models.CharField(max_length=100)),
                ("url", models.URLField()),
                ("region", models.CharField(max_length=100)),
                ("start_year", models.IntegerField(max_length=100)),
                ("impact", models.CharField(max_length=100)),
                ("added", models.DateTimeField()),
                ("published", models.DateTimeField()),
                ("country", models.CharField(max_length=100)),
                ("relevance", models.IntegerField(max_length=100)),
                ("pestle", models.CharField(max_length=100)),
                ("source", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("likelihood", models.IntegerField(max_length=100)),
            ],
        ),
    ]
