# Generated by Django 4.1.3 on 2023-05-11 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="School",
            new_name="json",
        ),
    ]
