# Generated by Django 4.1.3 on 2023-05-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_school_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="json",
            name="end_year",
            field=models.CharField(max_length=100),
        ),
    ]
