# Generated by Django 4.1.3 on 2023-05-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_json_end_year"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="json",
            new_name="jsondata",
        ),
    ]
