# Generated by Django 4.1.3 on 2023-05-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_rename_json_jsondata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jsondata",
            name="id",
        ),
        migrations.AlterField(
            model_name="jsondata",
            name="intensity",
            field=models.IntegerField(
                max_length=100, primary_key=True, serialize=False
            ),
        ),
    ]
