# Generated by Django 4.1.3 on 2023-05-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_jsondata_added_alter_jsondata_published_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="json",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("end_year", models.CharField(max_length=100)),
                ("intensity", models.IntegerField()),
                ("sector", models.CharField(max_length=100)),
                ("topic", models.CharField(max_length=100)),
                ("insight", models.CharField(max_length=100)),
                ("url", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
                ("start_year", models.CharField(max_length=100)),
                ("impact", models.CharField(max_length=100)),
                ("added", models.CharField(max_length=100)),
                ("published", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("relevance", models.IntegerField()),
                ("pestle", models.CharField(max_length=100)),
                ("source", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("likelihood", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="jsondata",
        ),
    ]
